SpiderMonkey, jsawk and resty working with PPA binary

diff --git a/resources/docker-couchbase b/resources/docker-couchbase
--- a/resources/docker-couchbase
+++ b/resources/docker-couchbase
@@ -1,4 +1,5 @@
 #!/bin/bash
+source /usr/local/bin/resty -W 'http://localhost:8091/pools/default'
 
 function untilsuccessful() {
     "$@"
@@ -88,9 +89,6 @@ fi
 if [ -z "$PASSWORD" ]; then
 	PASSWORD="password"
 fi
-if [ -z "$CLUSTER_RAMSIZE" ]; then
-	CLUSTER_RAMSIZE=1000
-fi
 
 
 # Conditional logic based on command sent in
@@ -132,46 +130,62 @@ case "$1" in
 			echo "CREATE_SCRIPT not defined. This must be present and point to a valid bash script.";
 			exit 1;
 		else
-			echo "* creating buckets from "$CREATE_SCRIPT;
-			/opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=transactional_data \
-			--bucket-type=couchbase  \
-			--bucket-ramsize=450  \
-			--bucket-replica=0  \
-			--enable-flush=0  \
-			--wait
-			/opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=reference_data \
-			--bucket-type=couchbase  \
-			--bucket-ramsize=100  \
-			--bucket-replica=0  \
-			--enable-flush=1  \
-			--wait
-			/opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=oauth_data \
-			--bucket-type=couchbase  \
-			--bucket-ramsize=100  \
-			--bucket-replica=0  \
-			--enable-flush=1  \
-			--wait
-			/opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=lookups \
-			--bucket-type=couchbase  \
-			--bucket-ramsize=150  \
-			--bucket-replica=0  \
-			--enable-flush=1  \
-			--wait
-			/opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=user_data \
-			--bucket-type=couchbase  \
-			--bucket-ramsize=200  \
-			--bucket-replica=0  \
-			--enable-flush=1  \
-			--wait
-			
-			bucketList=$(untilsuccessful /opt/couchbase/bin/couchbase-cli bucket-list -c 127.0.0.1:8091 \
-				-u $USER -p $PASSWORD )
-			if [ -z "$bucketList" ]; then
-				echo "* Still no buckets defined post-transfer";
-			else
-				echo "* Bucket list post-transfer:";
-				echo $bucketList;
+			if [ -z "$CREATE_SCRIPT" ];then
+				CREATE_SCRIPT=default.conf
 			fi
+			echo "* creating buckets from "$CREATE_SCRIPT;
+			if [ -e /app/conf/$CREATE_SCRIPT ];then 
+				echo "     - creation script '$CREATE_SCRIPT' found on volume share";
+				printf "     - buckets to be configured: %s\n" `cat /app/conf/$CREATE_SCRIPT | jsawk 'return this.name'`;
+			else
+				echo "ERROR: could not find '/app/conf/$CREATE_SCRIPT'; stopping configuration/creation process";
+				exit 1;
+			fi
+			# set default bucketsize of 100 if not set explicitly
+			
+			
+			# define cluster ramsize as sum of bucket sizes unless explictly set
+			if [ -z "$CLUSTER_RAMSIZE" ]; then
+				echo "* Couchbase cluster size not explicit set (CLUSTER_RAMSIZE) so using aggregate of bucket sizes";
+				CLUSTER_RAMSIZE=1000
+			else
+				echo "* Couchbase cluster size was explicity set to $CLUSTER_RAMSIZE";
+			fi
+			
+			
+			# /opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=transactional_data \
+			# --bucket-type=couchbase  \
+			# --bucket-ramsize=450  \
+			# --bucket-replica=0  \
+			# --enable-flush=0  \
+			# --wait
+			# /opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=reference_data \
+			# --bucket-type=couchbase  \
+			# --bucket-ramsize=100  \
+			# --bucket-replica=0  \
+			# --enable-flush=1  \
+			# --wait
+			# /opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=oauth_data \
+			# --bucket-type=couchbase  \
+			# --bucket-ramsize=100  \
+			# --bucket-replica=0  \
+			# --enable-flush=1  \
+			# --wait
+			# /opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=lookups \
+			# --bucket-type=couchbase  \
+			# --bucket-ramsize=150  \
+			# --bucket-replica=0  \
+			# --enable-flush=1  \
+			# --wait
+			# /opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=user_data \
+			# --bucket-type=couchbase  \
+			# --bucket-ramsize=200  \
+			# --bucket-replica=0  \
+			# --enable-flush=1  \
+			# --wait
+			
+			echo "* Bucket list post-transfer:";
+			echo `GET /buckets | jsawk 'return this.name'`
 			
 			echo "* adding self to new Couchbase cluster";
 			/opt/couchbase/bin/couchbase-cli cluster-init -c 127.0.0.1:8091 --cluster-init-username=$USER --cluster-init-password=$PASSWORD --cluster-init-ramsize=$CLUSTER_RAMSIZE --wait
